import {
  trueTypeOf,
  isNull,
  isUndefined,
  isNullOrUndefined,
  isObject,
  isFunction,
  isBoolean,
  isNumber,
  isDate,
  isString,
  isRegExp,
  isArray,
} from './typeChecking';

import {
  objectErrorHandler,
  functionErrorHandler,
  booleanErrorHandler,
  numberErrorHandler,
  dateErrorHandler,
  stringErrorHandler,
  regexpErrorHandler,
  arrayErrorHandler,
} from './errorHandlers';

export {
  trueTypeOf,
  isNull,
  isUndefined,
  isNullOrUndefined,
  isObject,
  objectErrorHandler,
  isFunction,
  functionErrorHandler,
  isBoolean,
  booleanErrorHandler,
  isNumber,
  numberErrorHandler,
  isDate,
  dateErrorHandler,
  isString,
  stringErrorHandler,
  isRegExp,
  regexpErrorHandler,
  isArray,
  arrayErrorHandler,
};

export default {
  trueTypeOf,
  isNull,
  isUndefined,
  isNullOrUndefined,
  isObject,
  objectErrorHandler,
  isFunction,
  functionErrorHandler,
  isBoolean,
  booleanErrorHandler,
  isNumber,
  numberErrorHandler,
  isDate,
  dateErrorHandler,
  isString,
  stringErrorHandler,
  isRegExp,
  regexpErrorHandler,
  isArray,
  arrayErrorHandler,
};
